package br.com.g2sapps.lotofacil.principal;

import br.com.g2sapps.lotofacil.dominio.Gerador;
import br.com.g2sapps.lotofacil.dominio.Jogo;
import br.com.g2sapps.lotofacil.dominio.LoteriasCaixa;
import br.com.g2sapps.lotofacil.negocio.ValidarColunaIncompleta;
import br.com.g2sapps.lotofacil.negocio.ValidarLimiteDeNumerosPorLinha;
import br.com.g2sapps.lotofacil.negocio.ValidarLinhaIncompleta;
import br.com.g2sapps.lotofacil.negocio.ValidarNumerosPrimos;
import br.com.g2sapps.lotofacil.negocio.ValidarNumerosRepetidos;
import br.com.g2sapps.lotofacil.negocio.ValidarParesEImpares;
import br.com.g2sapps.lotofacil.negocio.ValidarSoma;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JLabel;
import br.com.g2sapps.lotofacil.negocio.RegraDeNegocio;

public class GeradorDeJogo extends javax.swing.JFrame {

    private final List<Integer> numerosFixos;
    private final List<Integer> numerosRemovidos;
    private List<Integer> numerosSorteadosNoUltimoConcurso;
    private final ValidarNumerosRepetidos validarNumerosRepetidos;
    private final ValidarParesEImpares validarParesEImpares;
    private final ValidarSoma validarSoma;
    private ValidarLimiteDeNumerosPorLinha validarLimiteDeNumerosPorLinha;
    private final ValidarLinhaIncompleta validarLinhaIncompleta;
    private final ValidarColunaIncompleta validarColunaIncompleta;
    private final ValidarNumerosPrimos validarNumerosPrimos;
    private final List<RegraDeNegocio> regrasDeNegocio;
    private boolean botaoDesabilitadoPorFixarOuRemover;
    private boolean botaoDesabilitadoPorQuantidadeDeNumerosPrimosEntre;
    private final List<JLabel> numerosLabels;

    public GeradorDeJogo() {
        initComponents();
        numerosFixos = new ArrayList<>();
        numerosRemovidos = new ArrayList<>();
        inicializarNumerosSorteadosNoUltimoConcurso();
        validarNumerosRepetidos = new ValidarNumerosRepetidos(numerosSorteadosNoUltimoConcurso);
        validarParesEImpares = new ValidarParesEImpares();
        validarSoma = new ValidarSoma();
        validarLimiteDeNumerosPorLinha = new ValidarLimiteDeNumerosPorLinha();
        validarLinhaIncompleta = new ValidarLinhaIncompleta();
        validarColunaIncompleta = new ValidarColunaIncompleta();
        validarNumerosPrimos = new ValidarNumerosPrimos();
        regrasDeNegocio = new ArrayList<>();
        numerosLabels = new ArrayList<>(Arrays.asList(numero1Label, numero2Label, numero3Label, numero4Label, numero5Label, numero6Label, numero7Label, numero8Label, numero9Label, numero10Label, numero11Label, numero12Label, numero13Label, numero14Label, numero15Label, numero16Label, numero17Label, numero18Label, numero19Label, numero20Label, numero21Label, numero22Label, numero23Label, numero24Label, numero25Label));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        numerosFixosList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        numerosRemovidosList = new javax.swing.JList<>();
        fixarERemoverLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        oitoNumerosRepetidosRadioButton = new javax.swing.JRadioButton();
        noveNumerosRepetidosRadioButton = new javax.swing.JRadioButton();
        dezNumerosRepetidosRadioButton = new javax.swing.JRadioButton();
        oitoNoveOuDezNumerosRepetidosRadioButton = new javax.swing.JRadioButton();
        entre5E15NumerosRepetidosRadioButton = new javax.swing.JRadioButton();
        quantidadeDeNumerosRepetidosLabel = new javax.swing.JLabel();
        validarParesEImparesCheckBox = new javax.swing.JCheckBox();
        somaEntre171E220CheckBox = new javax.swing.JCheckBox();
        validarLimiteDeNumerosPorLinhaCheckBox = new javax.swing.JCheckBox();
        naoCompletarLinhaCheckBox = new javax.swing.JCheckBox();
        naoCompletarColunaCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        minimoDeNumerosPrimosSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        maximoDeNumerosPrimosSpinner = new javax.swing.JSpinner();
        quantidadeDeNumerosPrimosEntreLabel = new javax.swing.JLabel();
        gerarJogoButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        numero1Label = new javax.swing.JLabel();
        numero2Label = new javax.swing.JLabel();
        numero3Label = new javax.swing.JLabel();
        numero4Label = new javax.swing.JLabel();
        numero5Label = new javax.swing.JLabel();
        numero6Label = new javax.swing.JLabel();
        numero7Label = new javax.swing.JLabel();
        numero8Label = new javax.swing.JLabel();
        numero9Label = new javax.swing.JLabel();
        numero10Label = new javax.swing.JLabel();
        numero11Label = new javax.swing.JLabel();
        numero12Label = new javax.swing.JLabel();
        numero13Label = new javax.swing.JLabel();
        numero14Label = new javax.swing.JLabel();
        numero15Label = new javax.swing.JLabel();
        numero16Label = new javax.swing.JLabel();
        numero17Label = new javax.swing.JLabel();
        numero18Label = new javax.swing.JLabel();
        numero19Label = new javax.swing.JLabel();
        numero20Label = new javax.swing.JLabel();
        numero21Label = new javax.swing.JLabel();
        numero22Label = new javax.swing.JLabel();
        numero23Label = new javax.swing.JLabel();
        numero24Label = new javax.swing.JLabel();
        numero25Label = new javax.swing.JLabel();
        repetidosLabel = new javax.swing.JLabel();
        paresImparesLabel = new javax.swing.JLabel();
        somaLabel = new javax.swing.JLabel();
        primosLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de jogo - Lotofácil");

        jPanel1.setPreferredSize(new java.awt.Dimension(460, 516));

        jLabel1.setText("Fixar:");

        numerosFixosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        numerosFixosList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                numerosFixosListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(numerosFixosList);

        jLabel2.setText("Remover:");

        numerosRemovidosList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        numerosRemovidosList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                numerosRemovidosListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(numerosRemovidosList);

        fixarERemoverLabel.setForeground(java.awt.Color.red);
        fixarERemoverLabel.setText(" ");

        jLabel3.setText("Quantidade de números repetidos do último concurso:");

        buttonGroup1.add(oitoNumerosRepetidosRadioButton);
        oitoNumerosRepetidosRadioButton.setText("8");
        oitoNumerosRepetidosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoNumerosRepetidosRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(noveNumerosRepetidosRadioButton);
        noveNumerosRepetidosRadioButton.setText("9");
        noveNumerosRepetidosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveNumerosRepetidosRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(dezNumerosRepetidosRadioButton);
        dezNumerosRepetidosRadioButton.setText("10");
        dezNumerosRepetidosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dezNumerosRepetidosRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(oitoNoveOuDezNumerosRepetidosRadioButton);
        oitoNoveOuDezNumerosRepetidosRadioButton.setText("8, 9 ou 10");
        oitoNoveOuDezNumerosRepetidosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoNoveOuDezNumerosRepetidosRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(entre5E15NumerosRepetidosRadioButton);
        entre5E15NumerosRepetidosRadioButton.setText("Entre 5 e 15");
        entre5E15NumerosRepetidosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entre5E15NumerosRepetidosRadioButtonActionPerformed(evt);
            }
        });

        quantidadeDeNumerosRepetidosLabel.setForeground(java.awt.Color.red);
        quantidadeDeNumerosRepetidosLabel.setText(" ");

        validarParesEImparesCheckBox.setText("7 pares e 8 ímpares, 8 pares e 7 ímpares ou 6 pares e 9 ímpares");
        validarParesEImparesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarParesEImparesCheckBoxActionPerformed(evt);
            }
        });

        somaEntre171E220CheckBox.setText("Soma entre 171 e 220");
        somaEntre171E220CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaEntre171E220CheckBoxActionPerformed(evt);
            }
        });

        validarLimiteDeNumerosPorLinhaCheckBox.setText("4 números numa linha, 2 em outra e 3 nas demais");
        validarLimiteDeNumerosPorLinhaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarLimiteDeNumerosPorLinhaCheckBoxActionPerformed(evt);
            }
        });

        naoCompletarLinhaCheckBox.setText("Não completar linha");
        naoCompletarLinhaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoCompletarLinhaCheckBoxActionPerformed(evt);
            }
        });

        naoCompletarColunaCheckBox.setText("Não completar coluna");
        naoCompletarColunaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoCompletarColunaCheckBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade de números primos entre:");

        minimoDeNumerosPrimosSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        minimoDeNumerosPrimosSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                minimoDeNumerosPrimosSpinnerStateChanged(evt);
            }
        });

        jLabel5.setText("e");

        maximoDeNumerosPrimosSpinner.setModel(new javax.swing.SpinnerNumberModel(9, 0, 9, 1));
        maximoDeNumerosPrimosSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maximoDeNumerosPrimosSpinnerStateChanged(evt);
            }
        });

        quantidadeDeNumerosPrimosEntreLabel.setForeground(java.awt.Color.red);
        quantidadeDeNumerosPrimosEntreLabel.setText(" ");

        gerarJogoButton.setText("Gerar jogo");
        gerarJogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarJogoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(fixarERemoverLabel)
                    .addComponent(validarParesEImparesCheckBox)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(oitoNumerosRepetidosRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(noveNumerosRepetidosRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(dezNumerosRepetidosRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(oitoNoveOuDezNumerosRepetidosRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(entre5E15NumerosRepetidosRadioButton))
                    .addComponent(quantidadeDeNumerosRepetidosLabel)
                    .addComponent(somaEntre171E220CheckBox)
                    .addComponent(validarLimiteDeNumerosPorLinhaCheckBox)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(naoCompletarLinhaCheckBox)
                        .addGap(79, 79, 79)
                        .addComponent(naoCompletarColunaCheckBox))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minimoDeNumerosPrimosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximoDeNumerosPrimosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quantidadeDeNumerosPrimosEntreLabel)
                    .addComponent(gerarJogoButton))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fixarERemoverLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oitoNumerosRepetidosRadioButton)
                    .addComponent(noveNumerosRepetidosRadioButton)
                    .addComponent(dezNumerosRepetidosRadioButton)
                    .addComponent(oitoNoveOuDezNumerosRepetidosRadioButton)
                    .addComponent(entre5E15NumerosRepetidosRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantidadeDeNumerosRepetidosLabel)
                .addGap(18, 18, 18)
                .addComponent(validarParesEImparesCheckBox)
                .addGap(18, 18, 18)
                .addComponent(somaEntre171E220CheckBox)
                .addGap(18, 18, 18)
                .addComponent(validarLimiteDeNumerosPorLinhaCheckBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naoCompletarLinhaCheckBox)
                    .addComponent(naoCompletarColunaCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(minimoDeNumerosPrimosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(maximoDeNumerosPrimosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantidadeDeNumerosPrimosEntreLabel)
                .addGap(18, 18, 18)
                .addComponent(gerarJogoButton)
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel2.setPreferredSize(new java.awt.Dimension(367, 516));

        numero1Label.setBackground(java.awt.Color.white);
        numero1Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero1Label.setText("1");
        numero1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero1Label.setOpaque(true);

        numero2Label.setBackground(java.awt.Color.white);
        numero2Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero2Label.setText("2");
        numero2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero2Label.setOpaque(true);

        numero3Label.setBackground(java.awt.Color.white);
        numero3Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero3Label.setText("3");
        numero3Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero3Label.setOpaque(true);

        numero4Label.setBackground(java.awt.Color.white);
        numero4Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero4Label.setText("4");
        numero4Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero4Label.setOpaque(true);

        numero5Label.setBackground(java.awt.Color.white);
        numero5Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero5Label.setText("5");
        numero5Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero5Label.setOpaque(true);

        numero6Label.setBackground(java.awt.Color.white);
        numero6Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero6Label.setText("6");
        numero6Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero6Label.setOpaque(true);

        numero7Label.setBackground(java.awt.Color.white);
        numero7Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero7Label.setText("7");
        numero7Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero7Label.setOpaque(true);

        numero8Label.setBackground(java.awt.Color.white);
        numero8Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero8Label.setText("8");
        numero8Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero8Label.setOpaque(true);

        numero9Label.setBackground(java.awt.Color.white);
        numero9Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero9Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero9Label.setText("9");
        numero9Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero9Label.setOpaque(true);

        numero10Label.setBackground(java.awt.Color.white);
        numero10Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero10Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero10Label.setText("10");
        numero10Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero10Label.setOpaque(true);

        numero11Label.setBackground(java.awt.Color.white);
        numero11Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero11Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero11Label.setText("11");
        numero11Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero11Label.setOpaque(true);

        numero12Label.setBackground(java.awt.Color.white);
        numero12Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero12Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero12Label.setText("12");
        numero12Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero12Label.setOpaque(true);

        numero13Label.setBackground(java.awt.Color.white);
        numero13Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero13Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero13Label.setText("13");
        numero13Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero13Label.setOpaque(true);

        numero14Label.setBackground(java.awt.Color.white);
        numero14Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero14Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero14Label.setText("14");
        numero14Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero14Label.setOpaque(true);

        numero15Label.setBackground(java.awt.Color.white);
        numero15Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero15Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero15Label.setText("15");
        numero15Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero15Label.setOpaque(true);

        numero16Label.setBackground(java.awt.Color.white);
        numero16Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero16Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero16Label.setText("16");
        numero16Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero16Label.setOpaque(true);

        numero17Label.setBackground(java.awt.Color.white);
        numero17Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero17Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero17Label.setText("17");
        numero17Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero17Label.setOpaque(true);

        numero18Label.setBackground(java.awt.Color.white);
        numero18Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero18Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero18Label.setText("18");
        numero18Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero18Label.setOpaque(true);

        numero19Label.setBackground(java.awt.Color.white);
        numero19Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero19Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero19Label.setText("19");
        numero19Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero19Label.setOpaque(true);

        numero20Label.setBackground(java.awt.Color.white);
        numero20Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero20Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero20Label.setText("20");
        numero20Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero20Label.setOpaque(true);

        numero21Label.setBackground(java.awt.Color.white);
        numero21Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero21Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero21Label.setText("21");
        numero21Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero21Label.setOpaque(true);

        numero22Label.setBackground(java.awt.Color.white);
        numero22Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero22Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero22Label.setText("22");
        numero22Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero22Label.setOpaque(true);

        numero23Label.setBackground(java.awt.Color.white);
        numero23Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero23Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero23Label.setText("23");
        numero23Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero23Label.setOpaque(true);

        numero24Label.setBackground(java.awt.Color.white);
        numero24Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero24Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero24Label.setText("24");
        numero24Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero24Label.setOpaque(true);

        numero25Label.setBackground(java.awt.Color.white);
        numero25Label.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        numero25Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numero25Label.setText("25");
        numero25Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numero25Label.setOpaque(true);

        repetidosLabel.setText("Repetidos: 0");

        paresImparesLabel.setText("Pares: 0; ímpares: 0");

        somaLabel.setText("Soma: 0");

        primosLabel.setText("Primos: 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numero1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numero6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numero11Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero12Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero13Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero14Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero15Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numero16Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero17Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero18Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero19Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero20Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numero21Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero22Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero23Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero24Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numero25Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(repetidosLabel)
                    .addComponent(paresImparesLabel)
                    .addComponent(somaLabel)
                    .addComponent(primosLabel))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero8Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero11Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero12Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero13Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero14Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero15Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero16Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero17Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero18Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero19Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero20Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero21Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero22Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero23Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero24Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero25Label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(repetidosLabel)
                .addGap(18, 18, 18)
                .addComponent(paresImparesLabel)
                .addGap(18, 18, 18)
                .addComponent(somaLabel)
                .addGap(18, 18, 18)
                .addComponent(primosLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numerosFixosListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_numerosFixosListValueChanged
        boolean contemValoresSelecionadosIguais = fixarERemoverContemValoresSelecionadosIguais();
        botaoDesabilitadoPorFixarOuRemover = contemValoresSelecionadosIguais;
        definirBotaoDesabilitado(contemValoresSelecionadosIguais);
        exibirMensagem(contemValoresSelecionadosIguais);
    }//GEN-LAST:event_numerosFixosListValueChanged

    private void numerosRemovidosListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_numerosRemovidosListValueChanged
        boolean contemValoresSelecionadosIguais = fixarERemoverContemValoresSelecionadosIguais();
        botaoDesabilitadoPorFixarOuRemover = contemValoresSelecionadosIguais;
        definirBotaoDesabilitado(contemValoresSelecionadosIguais);
        exibirMensagem(contemValoresSelecionadosIguais);
    }//GEN-LAST:event_numerosRemovidosListValueChanged

    private void oitoNumerosRepetidosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoNumerosRepetidosRadioButtonActionPerformed
        if (oitoNumerosRepetidosRadioButton.isSelected()) {
            adicionarSeNaoContiver(validarNumerosRepetidos);
            validarNumerosRepetidos.setMinimo(8);
            validarNumerosRepetidos.setMaximo(8);
        }
    }//GEN-LAST:event_oitoNumerosRepetidosRadioButtonActionPerformed

    private void noveNumerosRepetidosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveNumerosRepetidosRadioButtonActionPerformed
        if (noveNumerosRepetidosRadioButton.isSelected()) {
            adicionarSeNaoContiver(validarNumerosRepetidos);
            validarNumerosRepetidos.setMinimo(9);
            validarNumerosRepetidos.setMaximo(9);
        }
    }//GEN-LAST:event_noveNumerosRepetidosRadioButtonActionPerformed

    private void dezNumerosRepetidosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dezNumerosRepetidosRadioButtonActionPerformed
        if (dezNumerosRepetidosRadioButton.isSelected()) {
            adicionarSeNaoContiver(validarNumerosRepetidos);
            validarNumerosRepetidos.setMinimo(10);
            validarNumerosRepetidos.setMaximo(10);
        }
    }//GEN-LAST:event_dezNumerosRepetidosRadioButtonActionPerformed

    private void oitoNoveOuDezNumerosRepetidosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoNoveOuDezNumerosRepetidosRadioButtonActionPerformed
        if (oitoNoveOuDezNumerosRepetidosRadioButton.isSelected()) {
            adicionarSeNaoContiver(validarNumerosRepetidos);
            validarNumerosRepetidos.setMinimo(8);
            validarNumerosRepetidos.setMaximo(10);
        }
    }//GEN-LAST:event_oitoNoveOuDezNumerosRepetidosRadioButtonActionPerformed

    private void entre5E15NumerosRepetidosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entre5E15NumerosRepetidosRadioButtonActionPerformed
        if (entre5E15NumerosRepetidosRadioButton.isSelected()) {
            regrasDeNegocio.remove(validarNumerosRepetidos);
        }
    }//GEN-LAST:event_entre5E15NumerosRepetidosRadioButtonActionPerformed

    private void validarParesEImparesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarParesEImparesCheckBoxActionPerformed
        if (validarParesEImparesCheckBox.isSelected()) {
            regrasDeNegocio.add(validarParesEImpares);
        } else {
            regrasDeNegocio.remove(validarParesEImpares);
        }
    }//GEN-LAST:event_validarParesEImparesCheckBoxActionPerformed

    private void somaEntre171E220CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaEntre171E220CheckBoxActionPerformed
        if (somaEntre171E220CheckBox.isSelected()) {
            regrasDeNegocio.add(validarSoma);
        } else {
            regrasDeNegocio.remove(validarSoma);
        }
    }//GEN-LAST:event_somaEntre171E220CheckBoxActionPerformed

    private void validarLimiteDeNumerosPorLinhaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarLimiteDeNumerosPorLinhaCheckBoxActionPerformed
        if (validarLimiteDeNumerosPorLinhaCheckBox.isSelected()) {
            regrasDeNegocio.add(validarLimiteDeNumerosPorLinha);
            regrasDeNegocio.remove(validarLinhaIncompleta);
            naoCompletarLinhaCheckBox.setSelected(true);
            naoCompletarLinhaCheckBox.setEnabled(false);
        } else {
            regrasDeNegocio.remove(validarLimiteDeNumerosPorLinha);
            naoCompletarLinhaCheckBox.setSelected(false);
            naoCompletarLinhaCheckBox.setEnabled(true);
        }
    }//GEN-LAST:event_validarLimiteDeNumerosPorLinhaCheckBoxActionPerformed

    private void naoCompletarLinhaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoCompletarLinhaCheckBoxActionPerformed
        if (naoCompletarLinhaCheckBox.isSelected()) {
            regrasDeNegocio.add(validarLinhaIncompleta);
        } else {
            regrasDeNegocio.remove(validarLinhaIncompleta);
        }
    }//GEN-LAST:event_naoCompletarLinhaCheckBoxActionPerformed

    private void naoCompletarColunaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoCompletarColunaCheckBoxActionPerformed
        if (naoCompletarColunaCheckBox.isSelected()) {
            regrasDeNegocio.add(validarColunaIncompleta);
        } else {
            regrasDeNegocio.remove(validarColunaIncompleta);
        }
    }//GEN-LAST:event_naoCompletarColunaCheckBoxActionPerformed

    private void minimoDeNumerosPrimosSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_minimoDeNumerosPrimosSpinnerStateChanged
        int minimo = (int) minimoDeNumerosPrimosSpinner.getValue();
        int maximo = (int) maximoDeNumerosPrimosSpinner.getValue();
        if (!validarQuantidadeDeNumerosPrimosEntre(minimo, maximo)) {
            return;
        }
        adicionarOuRemoverValidarNumerosPrimos(minimo, maximo);
    }//GEN-LAST:event_minimoDeNumerosPrimosSpinnerStateChanged

    private void maximoDeNumerosPrimosSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maximoDeNumerosPrimosSpinnerStateChanged
        int minimo = (int) minimoDeNumerosPrimosSpinner.getValue();
        int maximo = (int) maximoDeNumerosPrimosSpinner.getValue();
        if (!validarQuantidadeDeNumerosPrimosEntre(minimo, maximo)) {
            return;
        }
        adicionarOuRemoverValidarNumerosPrimos(minimo, maximo);
    }//GEN-LAST:event_maximoDeNumerosPrimosSpinnerStateChanged

    private void gerarJogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarJogoButtonActionPerformed
        boolean jogoRealizadoComSucesso = false;
        for (JLabel jLabel : numerosLabels) {
            jLabel.setBackground(Color.WHITE);
        }
        numerosFixos.clear();
        numerosRemovidos.clear();
        for (String numeroFixo : numerosFixosList.getSelectedValuesList()) {
            numerosFixos.add(Integer.valueOf(numeroFixo));
        }
        for (String numeroRemovido : numerosRemovidosList.getSelectedValuesList()) {
            numerosRemovidos.add(Integer.valueOf(numeroRemovido));
        }
        do {
            try {
                preencherAreaDosNumerosEscolhidos(numerosFixos, numerosRemovidos);
                jogoRealizadoComSucesso = true;
            } catch (Exception e) {
                System.err.println(e.getMessage());
            } finally {
                restaurarValidarLimiteDeNumerosPorLinhaSeSelecionado();
            }
        } while (!jogoRealizadoComSucesso);
    }//GEN-LAST:event_gerarJogoButtonActionPerformed

    private void inicializarNumerosSorteadosNoUltimoConcurso() {
        try {
            numerosSorteadosNoUltimoConcurso = LoteriasCaixa.obterNumerosSorteadosNoUltimoConcurso();
        } catch (Exception e) {
            numerosSorteadosNoUltimoConcurso = new ArrayList<>();
            Enumeration<AbstractButton> enumeration = buttonGroup1.getElements();
            while (enumeration.hasMoreElements()) {
                enumeration.nextElement().setEnabled(false);
            }
            quantidadeDeNumerosRepetidosLabel.setText("Erro ao obter resultado do último concurso");
        }
    }

    private boolean fixarERemoverContemValoresSelecionadosIguais() {
        for (String valorSelecionado : numerosFixosList.getSelectedValuesList()) {
            if (numerosRemovidosList.getSelectedValuesList().contains(valorSelecionado)) {
                return true;
            }
        }
        return false;
    }

    private void exibirMensagem(boolean fixarERemoverContemValoresSelecionadosIguais) {
        fixarERemoverLabel.setText(fixarERemoverContemValoresSelecionadosIguais ? "Fixar e Remover contêm valores iguais" : " ");
    }

    private boolean validarQuantidadeDeNumerosPrimosEntre(int minimo, int maximo) {
        boolean valida = maximo >= minimo;
        quantidadeDeNumerosPrimosEntreLabel.setText(valida ? " " : "Valores inválidos");
        botaoDesabilitadoPorQuantidadeDeNumerosPrimosEntre = !valida;
        definirBotaoDesabilitado(!valida);
        return valida;
    }

    private void definirBotaoDesabilitado(boolean b) {
        if (b) {
            gerarJogoButton.setEnabled(false);
        } else if (!botaoDesabilitadoPorFixarOuRemover && !botaoDesabilitadoPorQuantidadeDeNumerosPrimosEntre) {
            gerarJogoButton.setEnabled(true);
        }
    }

    private void adicionarOuRemoverValidarNumerosPrimos(int minimo, int maximo) {
        if (minimo == 0 && maximo == 9) {
            regrasDeNegocio.remove(validarNumerosPrimos);
        } else {
            validarNumerosPrimos.setMinimo(minimo);
            validarNumerosPrimos.setMaximo(maximo);
            adicionarSeNaoContiver(validarNumerosPrimos);
        }
    }

    private void adicionarSeNaoContiver(RegraDeNegocio regraDeNegocio) {
        if (!regrasDeNegocio.contains(regraDeNegocio)) {
            regrasDeNegocio.add(regraDeNegocio);
        }
    }

    private void preencherAreaDosNumerosEscolhidos(List<Integer> numerosFixos, List<Integer> numerosRemovidos) throws Exception {
        Gerador apostador = new Gerador();
        apostador.fixarNumeros(numerosFixos);
        apostador.removerNumeros(numerosRemovidos);
        Jogo jogo = apostador.gerarJogo(regrasDeNegocio);
        List<Integer> numerosMarcados = jogo.getListaDeNumerosMarcados();
        for (int numeroMarcado : numerosMarcados) {
            JLabel numeroLabel = numerosLabels.get(numeroMarcado - 1);
            numeroLabel.setBackground(Color.PINK);
        }
        if (numerosSorteadosNoUltimoConcurso.isEmpty()) {
            repetidosLabel.setText("Repetidos: ");
        } else {
            repetidosLabel.setText("Repetidos: " + jogo.obterQuantidadeDeNumerosRepetidosDoUltimoConcurso(numerosSorteadosNoUltimoConcurso));
        }
        paresImparesLabel.setText("Pares: " + jogo.obterQuantidadeDeNumerosMarcadosPares() + "; ímpares: " + jogo.obterQuantidadeDeNumerosMarcadosImpares());
        somaLabel.setText("Soma: " + jogo.somarNumerosMarcados());
        primosLabel.setText("Primos: " + jogo.obterQuantidadeDeNumerosMarcadosPrimos());
    }

    private void restaurarValidarLimiteDeNumerosPorLinhaSeSelecionado() {
        if (validarLimiteDeNumerosPorLinhaCheckBox.isSelected()) {
            regrasDeNegocio.remove(validarLimiteDeNumerosPorLinha);
            validarLimiteDeNumerosPorLinha = new ValidarLimiteDeNumerosPorLinha();
            regrasDeNegocio.add(validarLimiteDeNumerosPorLinha);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeradorDeJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeradorDeJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeradorDeJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeradorDeJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeradorDeJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dezNumerosRepetidosRadioButton;
    private javax.swing.JRadioButton entre5E15NumerosRepetidosRadioButton;
    private javax.swing.JLabel fixarERemoverLabel;
    private javax.swing.JButton gerarJogoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner maximoDeNumerosPrimosSpinner;
    private javax.swing.JSpinner minimoDeNumerosPrimosSpinner;
    private javax.swing.JCheckBox naoCompletarColunaCheckBox;
    private javax.swing.JCheckBox naoCompletarLinhaCheckBox;
    private javax.swing.JRadioButton noveNumerosRepetidosRadioButton;
    private javax.swing.JLabel numero10Label;
    private javax.swing.JLabel numero11Label;
    private javax.swing.JLabel numero12Label;
    private javax.swing.JLabel numero13Label;
    private javax.swing.JLabel numero14Label;
    private javax.swing.JLabel numero15Label;
    private javax.swing.JLabel numero16Label;
    private javax.swing.JLabel numero17Label;
    private javax.swing.JLabel numero18Label;
    private javax.swing.JLabel numero19Label;
    private javax.swing.JLabel numero1Label;
    private javax.swing.JLabel numero20Label;
    private javax.swing.JLabel numero21Label;
    private javax.swing.JLabel numero22Label;
    private javax.swing.JLabel numero23Label;
    private javax.swing.JLabel numero24Label;
    private javax.swing.JLabel numero25Label;
    private javax.swing.JLabel numero2Label;
    private javax.swing.JLabel numero3Label;
    private javax.swing.JLabel numero4Label;
    private javax.swing.JLabel numero5Label;
    private javax.swing.JLabel numero6Label;
    private javax.swing.JLabel numero7Label;
    private javax.swing.JLabel numero8Label;
    private javax.swing.JLabel numero9Label;
    private javax.swing.JList<String> numerosFixosList;
    private javax.swing.JList<String> numerosRemovidosList;
    private javax.swing.JRadioButton oitoNoveOuDezNumerosRepetidosRadioButton;
    private javax.swing.JRadioButton oitoNumerosRepetidosRadioButton;
    private javax.swing.JLabel paresImparesLabel;
    private javax.swing.JLabel primosLabel;
    private javax.swing.JLabel quantidadeDeNumerosPrimosEntreLabel;
    private javax.swing.JLabel quantidadeDeNumerosRepetidosLabel;
    private javax.swing.JLabel repetidosLabel;
    private javax.swing.JCheckBox somaEntre171E220CheckBox;
    private javax.swing.JLabel somaLabel;
    private javax.swing.JCheckBox validarLimiteDeNumerosPorLinhaCheckBox;
    private javax.swing.JCheckBox validarParesEImparesCheckBox;
    // End of variables declaration//GEN-END:variables
}
